import { Schema, model, Document, Types } from 'mongoose'

export type OrderType = 'picking' | 'packing' | 'commissioning' | 'decommissioning' | 'shipping'
export type OrderStatus = 'pending' | 'in_progress' | 'completed' | 'cancelled'

export interface IOrderItem {
  lineNumber: string          // EWMDeliveryItem
  warehouseTask: string       // WarehouseTask number
  product: string             // Product / material number
  batch: string               // Batch / lot number
  quantity: number            // TargetQuantityInBaseUnit (planned)
  actualQuantity: number      // ActualQuantityInBaseUnit (confirmed)
  unit: string                // BaseUnit (e.g. "PC")
  sourceBin: string           // SourceStorageBin
  sourceStorageType: string   // SourceStorageType
  destinationBin: string      // DestinationStorageBin
  destinationStorageType: string
  weight: number              // WhseTaskNetWeight
  weightUnit: string          // WhseTaskNetWeightUnitOfMeasure
  scannedEpcs: string[]       // Barcodes scanned by operator on mobile
  sourceData: Record<string, unknown> // Full raw source record for audit / re-mapping
}

export interface IDeliveryOrder extends Document {
  tenantId: Types.ObjectId
  orderNumber: string         // EWMDelivery — primary business identifier
  orderType: OrderType        // Chosen by user at upload time
  warehouse: string           // EWMWarehouse
  status: OrderStatus
  /**
   * UUID generated once per file upload.
   * All orders created from the same file share this ID so they can be
   * grouped / queried together.
   */
  importBatchId: string
  sourceFormat: string        // 'sap_ewm_warehouse_task' | future formats
  items: IOrderItem[]
  /**
   * EPCIS XML stored as a string rather than a file so it survives
   * ephemeral filesystems (e.g. Render free tier).
   * Generated by the backend when the operator submits from mobile.
   */
  epcisContent: string | null
  epcisGeneratedAt: Date | null
  completedAt: Date | null
  createdAt: Date
  updatedAt: Date
}

const orderItemSchema = new Schema<IOrderItem>({
  lineNumber: { type: String, default: '' },
  warehouseTask: { type: String, default: '' },
  product: { type: String, required: true },
  batch: { type: String, default: '' },
  quantity: { type: Number, default: 0 },
  actualQuantity: { type: Number, default: 0 },
  unit: { type: String, default: 'PC' },
  sourceBin: { type: String, default: '' },
  sourceStorageType: { type: String, default: '' },
  destinationBin: { type: String, default: '' },
  destinationStorageType: { type: String, default: '' },
  weight: { type: Number, default: 0 },
  weightUnit: { type: String, default: 'KG' },
  scannedEpcs: { type: [String], default: [] },
  sourceData: { type: Schema.Types.Mixed },
}, { _id: false })

const deliveryOrderSchema = new Schema<IDeliveryOrder>({
  tenantId: { type: Schema.Types.ObjectId, ref: 'Tenant', required: true, index: true },
  orderNumber: { type: String, required: true },
  orderType: {
    type: String,
    enum: ['picking', 'packing', 'commissioning', 'decommissioning', 'shipping'],
    required: true,
  },
  warehouse: { type: String, default: '' },
  status: {
    type: String,
    enum: ['pending', 'in_progress', 'completed', 'cancelled'],
    default: 'pending',
    index: true,
  },
  importBatchId: { type: String, required: true, index: true },
  sourceFormat: { type: String, default: 'sap_ewm_warehouse_task' },
  items: [orderItemSchema],
  epcisContent: { type: String, default: null },
  epcisGeneratedAt: { type: Date, default: null },
  completedAt: { type: Date, default: null },
}, { timestamps: true })

// Compound index for efficient tenant + order queries
deliveryOrderSchema.index({ tenantId: 1, orderNumber: 1 })
deliveryOrderSchema.index({ tenantId: 1, status: 1 })
deliveryOrderSchema.index({ tenantId: 1, orderType: 1 })

export const DeliveryOrder = model<IDeliveryOrder>('DeliveryOrder', deliveryOrderSchema)
